name: OpenAI API Integration

on:
  workflow_dispatch: # 手动触发工作流

jobs:
  openai-api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Test OpenAI API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -c "import openai; openai.api_key='${{ secrets.OPENAI_API_KEY }}'; print(openai.Completion.create(model='text-davinci-003', prompt='Hello, world!', max_tokens=5))"
